defaults:
  - labeller: golden
  - data: test
  - al: random

experiment_name: test2
name: test2
output_dir: outputs
offline_mode: False
cache_dir: cache
seed: 42
al:
    init_query_size: 42
    query_size: 20
    num_iterations: 3
    evaluate_zero_iteration: True
    subsample_size: -1
    required_performance:
        rouge1: 0.5
    budget:

model:
    checkpoint: Qwen/Qwen2.5-1.5B-Instruct
    quantize: False
    model_max_length: ${multiply_with_few_shot:${data.input_max_length},${data.few_shot.count}}
    dtype: bfloat16
    save_in_fp_32: false
    peft:
        use: True
        r: 16
        lora_alpha: 16
        lora_dropout: 0.1
        bias: 'none'
        seed: ${seed}
        use_gradient_checkpointing: 'unsloth'
        modules:

training:
    dev_split_size: 0.2
    hyperparameters:
        num_epochs: 15
        train_batch_size: 64
        eval_batch_size: 64
        gradient_accumulation_steps: 1
        lr: 0.00003
        warmup_ratio: 0.03
        weight_decay: 0.01
        max_grad_norm: 1.
        early_stopping_patience: 10
        model_max_length: ${model.model_max_length}
        dataset_num_proc: ${data.num_proc}
        packing: False
        lr_scheduler_type: cosine
        gradient_checkpointing: True

inference:
    framework: 'vllm'
    max_new_tokens: ${data.output_max_length}
    batch_size: 8
    gpu_memory_utilization: 0.5
    temperature: 0.6
    top_p: 0.1
    model: ${model.checkpoint}

evaluation:
    additional_metrics:
        - alignscore
        - bartscore
    provider: openrouter
    base_url: https://openrouter.ai/api/v1
    api_key:
    model: anthropic/claude-3-7-sonnet
    deepeval_threshold: 0.5
    deepeval_include_reason: False
    deepeval_strict_mode: False
    deepeval_async_mode: True
    deepeval_verbose_mode: False
    deepeval_truths_extraction_limit: 10
    